### ISSUE TITLE
osv2osv doesn't support European parliament elections

### ISSUE THREAD

**Issue by hay** [openstate/osv2osv#1]
When using this tool to convert CSV's from the Dutch European Parliament elections 2019 i'm getting the error:

'not yet implemented election domain'

This seems to stem from line 335 in `lib.rs` where a check is done for either Waterschappen or Provinciale Staten verkiezingen. 

Is there anything i can do to force it to convert?

**Comment by bwbroersma** [comment]
See the [feature/EP+hashcode-finding](https://github.com/openstate/osv2osv/tree/feature/EP%2Bhashcode-finding) branch
